import React from 'react'

const contact = () => {
  return (
    <div>
      Contact
    </div>
  )
}

export const metadata = {
  title: "Contact",
  description: "Generated by @aditya-develops",
};

export default contact


