import React from 'react'

const about = () => {
  return (
    <div>
      About
    </div>
  )
}

export default about

export const metadata = {
  title: "About",
  description: "Generated by @aditya-develops",
};
