import localFont from "next/font/local";
import Navbar from "./component/Navbar";

export const metadata = {
  title: "Home",
  description: "Generated by @aditya-develops",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
